version: "3.3"

services:

  app:
    build: .
    depends_on: 
      - kafka
    command: mix deps.get
    environment:
      - MIX_ENV=dev
    volumes:
      - .:/app

  zookeeper:
      image: confluentinc/cp-zookeeper:5.5.1
      ports:
        - '32181:32181'
      environment:
        ZOOKEEPER_CLIENT_PORT: 32181
        ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:5.5.1
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    env_file: docker-compose-kafka.env
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:29092,EXTERNAL://localhost:9092
    healthcheck:
      test: kafka-topics --bootstrap-server kafka-1:29092 --list
      interval: 30s
      timeout: 10s
      retries: 4
    volumes:
      - ./ssl/kafka.server.keystore.jks:/etc/kafka/secrets/kafka.server.keystore.jks:ro,z
      - ./ssl/kafka.server.truststore.jks:/etc/kafka/secrets/kafka.server.truststore.jks:ro,z

  test:
    image: reconnect_app
    command: mix test
    environment:
      - MIX_ENV=test
    volumes_from:
      - app
    links:
      - kafka